// components/Home/Article.tsx
import Link from 'next/link'
import Image from 'next/image'
import comment from './actionBarImage/comment.png'
import arrow from './actionBarImage/arrow.png'
import mark from './actionBarImage/mark.png'
import share from './actionBarImage/share.png'
interface ArticleProps {
    userName: string,
    title: string,
    subtitle: string,
    count: number,
    id: number
}

export default function Article({ userName, title, subtitle, count, id }: ArticleProps) {

    return (
        <>
            <article className="article">
                <div className="article__content">
                    {/* <!-- header --> */}
                    <Link href="'/article/' + id">
                        <div className="article-header">
                            <img
                                className="article-header__user-icon"

                                src={require("../HeaderComponent/UserBarImage/avatar.png").default.src}
                            />
                            <div className="article-header__user-name">{userName}</div>
                        </div>
                        {/* <!-- title --> */}
                        <div className="article__title">{title}</div>
                        <div className="article__subtitle">{subtitle}</div>

                        {/* <!-- main image --> */}
                        <img className="article__image" src={require("./article.png").default.src} />
                    </Link>
                    {/* <!-- action bar --> */}
                    <div className="action-bar">
                        <div className="action-bar__column" style={{
                            width: '320px'
                        }}>
                            <button className="action-bar__icon">
                                <Image src={comment} alt="favorites" />
                            </button>

                            <button className="action-bar__icon">
                                <Image src={mark} alt="favorites" />
                            </button>

                            <button className="action-bar__icon">
                                <Image src={share} alt="favorites" />
                            </button>
                        </div>
                        <div className="action-bar__column">
                            <button className="action-bar__icon" >
                                <Image
                                    src={arrow}
                                    alt="favorites"

                                />
                            </button>
                            <div className="action-bar__count">{count}</div>
                            <button className="action-bar__icon action-bar__icon_mark" >
                                <Image
                                    src={arrow}
                                    alt="favorites"
                                />
                            </button>
                        </div>
                    </div>
                </div >
            </article >
        </>
    )
}

// components/Home/Article.vue
<template>
  <article class="article">
    <div class="article__content">
      <!-- header -->
      <Nuxt-link :to="'/article/' + id">
        <div class="article-header">
          <img
            class="article-header__user-icon"
            src="../HeaderComponent/UserBarImage/avatar.png"
          />
          <div class="article-header__user-name">{{ userName }}</div>
        </div>
        <!-- title -->
        <div class="article__title">{{ title }}</div>
        <div class="article__subtitle">{{ subtitle }}</div>

        <!-- main image -->
        <img class="article__image" src="./article.png" />
      </Nuxt-link>
      <!-- action bar -->
      <div class="action-bar">
        <div class="action-bar__column" style="width: 320px">
          <button class="action-bar__icon">
            <img src="./actionBarImage/comment.png" alt="favorites" />
          </button>

          <button class="action-bar__icon">
            <img src="./actionBarImage/mark.png" alt="favorites" />
          </button>

          <button class="action-bar__icon">
            <img src="./actionBarImage/share.png" alt="favorites" />
          </button>
        </div>
        <div class="action-bar__column">
          <button class="action-bar__icon" @click="()=> {
            this.count--
          }">
            <img
              src="./actionBarImage/arrow.png"
              alt="favorites"
              style="opacity: 0.5"
            />
          </button>
          <div class="action-bar__count">{{ count }}</div>
          <button class="action-bar__icon" @click="()=> {
            this.count++
          }">
            <img
              src="./actionBarImage/arrow.png"
              style="transform: scale(-1); opacity: 0.5"
              alt="favorites"
            />
          </button>
        </div>
      </div>
    </div>
  </article>
</template>
  
  <script>
export default {
  props: ["title", "subtitle", "userName", "count", "id"],
  data() {
    return {};
  },
};
</script>

  <style lang="scss">
.article {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 640px;
  height: 640px;
  background: rgb(253, 252, 252);
  border-radius: 10px;
  margin: 0 auto;
  &__content {
    padding: 20px;
    display: flex;
    flex-direction: column;
    align-items: left;
  }
  &__title {
    font-family: "Roboto";
    font-style: normal;
    font-weight: 400;
    font-size: 26px;
    line-height: 23px;
    color: rgb(23, 23, 23);
  }
  &__subtitle {
    margin-top: 10px;
    font-family: "Roboto";
    font-style: normal;
    font-weight: 400;
    font-size: 18px;
    line-height: 23px;
    color: rgb(23, 23, 23);
  }
  &__image {
    width: 100%;
    height: 405px;
  }
}
.article-header {
  width: 100%;
  height: 50px;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  &__user-icon {
    width: 30px;
    height: 30px;
  }
  &__user-name {
    margin-left: 10px;
  }
}

.action-bar {
  padding: 0 20px;
  height: 70px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  &__column {
    display: flex;
    align-items: center;
  }
  &__icon {
    width: 20px;
    height: 20px;
    margin: 0 20px;
    img {
      width: 100%;
      height: 100%;
    }
  }
  &__count {
    font-family: "Roboto";
    font-style: normal;
    font-weight: 400;
    font-size: 20px;
    line-height: 23px;
    color: rgb(71, 218, 52);
  }
}
</style>
